### ISSUE TITLE
Problems with Samsung Galaxy Y 

### ISSUE THREAD

**Issue by doperman** [sean111/terrariahb#16]
Hello!  I'm using a Samsung Galaxy Y (Model S5360)

Problems in using the app with this phone include missing pictures (i.e. screenshots of environments), and that the articles aren't compressed in the phone screen; some of the texts got stretched to the side, it's impossible to scroll to the side.  Is there a way this bug can be fixed? :)

**Comment by doperman** [comment]
The missing picture bug happens in the Environments and Mechanics section, while the expanding screen bug happens in the Environments and the NPCs section.

**Comment by sean111** [comment]
Thank you for taking the time to open an issue for this :). 

I am aware of the missing images and was working on a complete re-code of the application however the technology I was using will no longer be supported in Android so I will hopefully be going back and fixing the current version soon (been a little caught up in teaching myself UDK so I can make a game).

The text is an issue I have been battling since I created the application. The wiki's HTML is horrible which causes some issues when parsing the data and I heard that Android 4.0 makes it look a little worse. I need to re-do how it parses and displays the information.
